# Generated by Django 5.0.4 on 2024-05-20 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('products', '0002_remove_product_number_code_remove_product_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('net_value', models.FloatField()),
                ('tax_percentage', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
