# Generated by Django 5.0.6 on 2024-05-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('time_dimension', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timedimension',
            name='sk_year_month',
            field=models.CharField(blank=True, max_length=150, primary_key=True, serialize=False, unique=True),
        ),
    ]
