# Generated by Django 5.0.4 on 2024-05-14 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_ref_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('payment_mechanism', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('no', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=2)),
                ('date', models.DateField()),
                ('gross_total', models.FloatField()),
                ('tax_payable', models.FloatField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                              to='invoices.payment')),
            ],
        ),
    ]
