# Generated by Django 5.0.6 on 2024-05-25 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('time_dimension', '0002_alter_timedimension_sk_year_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net_total', models.FloatField()),
                ('sk', models.ForeignKey(db_column='sk_year_month', on_delete=django.db.models.deletion.CASCADE,
                                         related_name='sk_year_month_fact', to='time_dimension.timedimension')),
            ],
        ),
    ]
