# Generated by Django 5.0.4 on 2024-05-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('number_code', models.CharField(max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=10, default=0, max_digits=19)),
            ],
        ),
    ]
